#!/usr/bin/env python2

import gtk
import webkit
import gobject
import os


# init thread
gobject.threads_init()

window = gtk.Window()
window.set_title('Rdio for Linux')

# set size and position
window.set_default_size(1024, 700)
window.set_position(gtk.WIN_POS_CENTER)


def destroy(data=None):
    # terminates the current main loop
    gtk.main_quit()

# set icon
def get_resource_path(rel_path):
    dir_of_py_file = os.path.dirname(__file__)
    rel_path_to_resource = os.path.join(dir_of_py_file, rel_path)
    abs_path_to_resource = os.path.abspath(rel_path_to_resource)
    return abs_path_to_resource

window.set_icon_from_file(get_resource_path("icon.png"))

# create a scrolled window
scroll = gtk.ScrolledWindow()
scroll.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)

view = webkit.WebView()
browser = view.get_settings()
browser.set_property("enable-plugins", True)
browser.set_property("enable-private-browsing", True)
browser.set_property("enable-page-cache", True)
view.set_settings(browser)

view.open('https://www.rdio.com/signin/')

scroll.add(view)

# Menu Rdio
mb = gtk.MenuBar()

menu_rdio = gtk.Menu()
menu_rdio_i = gtk.MenuItem("Rdio")
menu_rdio_i.set_submenu(menu_rdio)


def menu_rdio_about(widget):
    about = gtk.AboutDialog()
    about.set_program_name("RDIO for Linux")
    about.set_comments("Application RDIO for Linux.")
    about.set_version("0.0.1")
    about.set_website("https://github.com/avelino/rdio-linux")
    about.set_logo(gtk.gdk.pixbuf_new_from_file_at_size("icon.png", 64, 64))
    about.run()
    about.destroy()

menu_rdio_i_about = gtk.MenuItem("About Rdio")
menu_rdio_i_about.connect("activate", menu_rdio_about)
menu_rdio.append(menu_rdio_i_about)

menu_rdio_i_exit = gtk.MenuItem("Quit Rdio")
menu_rdio_i_exit.connect("activate", destroy)
menu_rdio.append(menu_rdio_i_exit)

mb.append(menu_rdio_i)

# Render objects
vbox = gtk.VBox(False, 0)
vbox.pack_start(mb, False, False, 0)
vbox.pack_end(scroll, True, True, 0)

# Window render
window.add(vbox)

window.show_all()
window.connect('destroy', destroy)

gtk.main()
